In [15]:
%load_ext autoreload
%autoreload 2

from transition_parser import preprocess_conllu

device = "cuda:2"

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Influential members of the House Ways and Means Committee introduced legislation that would restrict how the new savings-and-loan bailout agency can raise capital , creating another potential obstacle to the government 's sale of sick thrifts .
The bill , whose backers include Chairman Dan Rostenkowski -LRB- D. , Ill. -RRB- , would prevent the Resolution Trust Corp. from raising temporary working capital by having an RTC-owned bank or thrift issue debt that would n't be counted on the federal budget .
The bill intends to restrict the RTC to Treasury borrowings only , unless the agency receives specific congressional authorization .
`` Such agency ` self-help ' borrowing is unauthorized and expensive , far more expensive than direct Treasury borrowing , '' said Rep. Fortney Stark -LRB- D. , Calif. -RRB- , the bill 's chief sponsor .
The complex financing plan in the S&L bailout law includes raising $ 30 billion from debt issued by the newly created RTC .
This financing system was create

In [48]:
from transformers import RobertaTokenizerFast, RobertaModel, RobertaForMaskedLM



In [51]:
model_name = "distilroberta-base"

tokenizer = RobertaTokenizerFast.from_pretrained(model_name)
model = RobertaForMaskedLM.from_pretrained(model_name).to(device)
raw_model = RobertaModel.from_pretrained(model_name).to(device)

Some weights of the model checkpoint at distilroberta-base were not used when initializing RobertaForMaskedLM: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [52]:
oktens = tokenizer("Hello, my dog is cute")

In [54]:
oktens

{'input_ids': [0, 31414, 6, 127, 2335, 16, 11962, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [55]:
for i in range(len(oktens['input_ids'])):
    print(oktens.token_to_chars(i))

None
CharSpan(start=0, end=5)
CharSpan(start=5, end=6)
CharSpan(start=7, end=9)
CharSpan(start=10, end=13)
CharSpan(start=14, end=16)
CharSpan(start=17, end=21)
None


In [38]:
[len(ok) for ok in oktens]

[3, 5, 1, 3, 4, 3, 5, 4]

In [76]:
in_str = "Influential members of the House"
input_data = tokenizer(in_str, return_tensors="pt")
input_ids = input_data['input_ids'][0].to(device)
attention_mask = input_data['attention_mask'][0].to(device)

In [77]:
data = raw_model(input_ids.unsqueeze(0), attention_mask.unsqueeze(0))

In [78]:
for i in range(len(in_str)):
    print(input_data.char_to_token(0, i))

1
1
1
2
2
3
3
3
3
3
3
None
4
4
4
4
4
4
4
None
5
5
None
6
6
6
None
7
7
7
7
7


In [33]:
print(data.keys())

odict_keys(['last_hidden_state', 'pooler_output'])


In [32]:
data['last_hidden_state'].shape

torch.Size([1, 8, 768])

In [34]:
data['pooler_output'].shape

torch.Size([1, 768])

In [79]:
preprocess_conllu('data/dev.conll', tokenizer, raw_model)

Influential
c 0 10
t 1 4
tensor([31288,  6487, 12986], device='cuda:2')
members
c 12 18
t 4 5
tensor([453], device='cuda:2')
of
c 20 21
t 5 6
tensor([9], device='cuda:2')
the
c 23 25
t 6 7
tensor([5], device='cuda:2')
House
c 27 31
t 7 8
tensor([446], device='cuda:2')
Ways
c 33 36
t 8 9
tensor([24049], device='cuda:2')
and
c 38 40
t 9 10
tensor([8], device='cuda:2')
Means
c 42 46
t 10 11
tensor([27088], device='cuda:2')
Committee
c 48 56
t 11 12
tensor([1674], device='cuda:2')
introduced
c 58 67
t 12 13
tensor([2942], device='cuda:2')
legislation
c 69 79
t 13 14
tensor([2309], device='cuda:2')
that
c 81 84
t 14 15
tensor([14], device='cuda:2')
would
c 86 90
t 15 16
tensor([74], device='cuda:2')
restrict
c 92 99
t 16 17
tensor([14058], device='cuda:2')
how
c 101 103
t 17 18
tensor([141], device='cuda:2')
the
c 105 107
t 18 19
tensor([5], device='cuda:2')
new
c 109 111
t 19 20
tensor([92], device='cuda:2')
savings-and-loan
c 113 128
t 20 26
tensor([4522,   12,  463,   12, 4082,  260], de